server:
  port: 8081
  servlet:
    session:
      cookie:
        secure: false      # Allow cookies on HTTP (only for localhost)
        http-only: true    # Still keeps it safe from JavaScript
        same-site: lax     # Better compatibility for localhost dev
      timeout: 30m
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liyOXeEU62MIxBqO
            client-secret: 93b0596e84091ac8e6648091b3e563ba4f725e14
            scope:
              - read: user
              - repo
              - notifications
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

  application:
    name: 0auth-githubtesting